### ISSUE TITLE
Concealed ship spawn issue

### ISSUE THREAD

**Issue by CJClaude** [SEServerExtender/SEServerExtender#11]
I know this is a known problem going back to the Tyrsis work, but in his documentation he claims this is very rare, and that a refresh should fix it.

That is not my experience.  Rather it is very common, and refreshing has no impact.

Just had it happen again, two medbays not visible on the respawn list, went to my station and both where nicely revealed AFTER I logged in:   http://puu.sh/gS1KV/6e771e6180.png

Note the 7 revealed entities AFTER the welcome back message.

This isn't critical, yet, but could become a major pain if I was off deep space exploring and couldn't get back to my ship.  Oh, vaguely related, the /admin move commands are broke too <smile>.

**Comment by dodexahedron** [comment]
There's a good chance that viewdistance screws with this.
I'll have a look at it after I fix some other outstanding show-stoppers.

**Comment by zrisher** [comment]
`/admin move player to` and `/admin move player position` are functioning properly for me, FYI on that additional issue.

**Comment by zrisher** [comment]
I have, however, experienced the same issue with Dynamic Conceal - spawn bays not appearing even with a refresh. 

I've also seen dynamic conceal completely remove grids, even when players return. They show up in the world file in the correct position, but they can't be seen, collided with, or interacted with. I also receive frequent server crashes when moving near those bugged concealed objects. If I disable DynamicConceal, they still don't show up and must be manually removed from the world file.

Soon after this happened, I noticed a strange collection of light effects at 0,0,0 that I believe are related. Numerous other people reported similar issues in this reddit thread:
http://www.reddit.com/r/spaceengineers/comments/32wm92/has_anyone_else_encountered_the_wisp_with_a_laser/

**Comment by zrisher** [comment]
I suggest this issue be renamed to "DynamicConceal fails to reveal spawn points" and marked as a bug

**Comment by dodexahedron** [comment]
There are a few fun things going on here.
First, concealment is taking advantage of an undocumented feature of the game - the InScene property of an entity.
If an entity is not marked as InScene, it is not subject to physics simulation (or any other stuff, but physics is the biggie), which is where the performance gains come from.  Concealment works by removing the InScene property, resulting in the ship disappearing.
However, InScene has some quirks:  First off, if there are light sources on the entity, it seems that not being InScene does not turn those lights off (that's why you get goofy light effects).  Also, one of the many properties that gets ignored when an entity is not InScene is its position.  However, position is made up of three doubles, and all structs in c# must have a value.  Thus, even though it is never initialized, the value of position is 0,0,0 for those entities.  Thus, they all show up at 0,0,0 in game (or at least their bugged lighting effects do), and tools like SEToolbox will also show them at 0,0,0.

Since no simulation whatsoever occurs for cubegrids that are not inscene, medbays are also not online, and thus you will never see them in the spawn menu.  Hitting refresh only works because of a tremor in the force (seriously - why that ever works is a complete freaking mystery, unless someone happens to have come close to where the medbay was).

This has been the case with InScene for at least the past 20 versions of SE and I'm thinking concealment is going to have to be completely reworked if Keen doesn't fix the behavior of InScene.

I'm thinking that perhaps concealment could actually just export the concealed CubeGrids to XML and then delete them from the world, for the time being.
The main problem with that, though, is that various cleanup tools people use would then consider character entities to be unused if all their cubegrids were removed from the XML.
Obviously the answer for that is for them to stop using those cleanup tools since the functionality can been easily replicated in SESE, but I'm just pointing the issue out.

**Comment by zrisher** [comment]
Thank you for the detailed explanation, that makes a lot of sense. 

I personally am still having a lot of trouble getting DynamicConceal to improve performance. Whenever I turn it on I get the expected 5-15 second lag spike, but CPU (and memory) only go up afterwards and I get a solid red line way off the top of the CTRL-H latency chart. If I disable it and reveal, 5-15 second predicted lag spike again and then CPU and latency return. But other people are currently using this successfully right?

I think removing the Cubegrids to XML sounds like it would produce more conceal/reveal lag but be significantly more reliable if Keen doesn't spend any time improving InScene's behavior.

**Comment by dodexahedron** [comment]
I won't be performing those actions on the same thread, so the lag should be minimal for conceal, but reveal lag could take a fairly significant hit, depending on the size (and number) of the cubegrids being revealed.

**Comment by zrisher** [comment]
How does dynamic conceal work with Cryobays? It seems like character entities stick around on the map in these. If we could just exclude cryobays with people in them instead of medbays, you would only ever have 1 grid per person that needed to not be concealed.

**Comment by dodexahedron** [comment]
You can't really do one instead of the other for the same reason that cryobays didn't really solve anything: when people crash or just forget to stop at a cryobay, they'd be screwed.

**Comment by zrisher** [comment]
What if we concealed everything (without an online player nearby), but when a player was online and didn't have a character entity in game, we reveal all their grids with medbays?

**Comment by FoxWyvern** [comment]
Adding the above requested feature, at least without giving it a True/False toggle in essentials would add an unnecessary load to the physics engine if there are worlds out there with a few grids with med bays and has a  large number of blocks. Below is my solution as it keeps large grids that don't need to be from being processed by the physics engine and still allows you to spawn where you want.

I....
     - Created a platform made up of 9 armor blocks, a solar panel, medical bay, beacon and a "Advanced Rotor".
     - Then set the beacon broadcast range to what ever my reveal/conceal distance, what I and everyone who is on my dedicated server does with all their beacons and antennas. 
     - Then added the line "LargeAdvancedStator" (ignoring quotation marks) to the Block Subtype Ignore List setting in Essentials.
     - Then removed the rotor top from the "Advanced Rotor" as to not create an unnecessary grid connection.
     - Then duplicated these platforms to the exact number of stations people have.
     - Moved one of these platforms around 300 meters away from everyone's stations.
     - Then renamed the Display Name (Info Tab) to: (R)"NAME OF STATION" (ignoring quotation marks and replacing NAME OF STATION with the name of the station it is sitting next to.)
     - Then renamed the Medical Bay to the same name as the grids Display Name (Info Tab).
     - Then transferred ownership of all blocks of each new spawn point platform to the owner of the station they are sitting next to.
     - Then just have Dynamic Conceal Large Ships with Med Bays set to true.

If you want to make the spawn point mobile because someone has a mobile base/station with a med bay. Just turn the new spawn point into a ship, add thrusters, gyros, and possibly fuel source in case it ends up not in the sun. Add a landing gear and lock the landing gear on the mobile station only when that station is traveling to a new destination, unlock it when it arrives. Leaving locked landing gear will cause both grids not to conceal, as do locked connectors, antenna/beacon relays, rotors, pistons, etc.

Hopes this helps...

**Comment by dodexahedron** [comment]
@FoxWyvern, are you able to meet up on TeamSpeak or Skype to chat about things?
I'd love to get a little real-time feedback from you.
I work my best if I have intense and open communication with people, in real-time.

**Comment by FoxWyvern** [comment]
@dodexahedron , TeamSpeak is best for me although I believe I have skype. I have a private TS server or I can connect to one, either is fine. Is there a way to send a private message on GetHub? I'm not very familiar with it sadly. :(

**Comment by FoxWyvern** [comment]
@dodexahedron if there is no private message option on GetHub, I guess just add me on steam. Here is a link to my profile: http://steamcommunity.com/profiles/76561197963215468/ we'll get in touch initially through there and exchange TS / Skype information as not to publically display it.

Additionally, I found Keen's forum's a good source to contact you through a private message which I did with related TS information.
