### ISSUE TITLE
[v1.127.09.187-alpha] Server chat not getting through

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#111]
Seems like to chat is not getting though either from messages I type via Extender, scheduled msgs, MOTD or welcome msgs. MOTD is not working either. I hope these big changes from Keen are for the best. Server is running and thats good, i'm patient.

**Comment by rexxar-tc** [comment]
I patched an issue with the client mod a few hours ago. Try restarting your server to get the new version.

**Comment by EngineerBean** [comment]
I got that patch just a few mins ago now, still same issue mate.

**Comment by rexxar-tc** [comment]
What you're describing happens when the client mod is in the mods list but isn't running. It works for me and the two other people I've had report issues, so it's probably something going on at your end.

First thing, make sure you're using mod 559202083 and not 558596580. The second one is the dev version of the mod.

Also, check your server log during startup and your client log for any mod compile errors.

**Comment by rexxar-tc** [comment]
Apparently there is an issue with mods in general this week. The Essentials mod works fine, but SE just won't run it. Keen should have this fixed on Thursday. In the meantime, either remove the essentials mod from your server, or put it at the very end of the list.

**Comment by EngineerBean** [comment]
It seems that the Holographic Radar was possibly causing a conflict. Something to do with session component. Since he updated with a workaround, problem with essentials has been resolved. Sorry to trouble you.
