### ISSUE TITLE
v1.79.8.411, entities list not fuction properly.

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#25]
Since the last update all entities like Large Ship, have not blocks or anything. Complete stations have no blocks, refinery's and such. Also the character entity stays empty while there are character on the server playing.

![untitled](https://cloud.githubusercontent.com/assets/6142706/7338864/e5ad4f3c-ec59-11e4-994d-a5af3769ea2a.png)

At the time of this screen shot there where 2 people active and not in a ship, so they should be visible in the entity screen.

Already tried several restarts and even making a new world, nothing seems to help.

![untitled](https://cloud.githubusercontent.com/assets/6142706/7338871/21acd200-ec5a-11e4-932e-7518e2f44103.png)

Here is a ship which I know has several blocks but none are shown in the entity tab.

SEServerExtender Log: http://pastebin.com/i42pEdm4
PluginLog: http://pastebin.com/etDtGTdf

Can't find anything that would cause this behavior

This might be an issue too, not sure if they are placed at the correct time, they seem to come in order of which commands I entered and when I pressed the entity tab, but seem delayed.

http://pastebin.com/LktkEQZr

**Comment by dodexahedron** [comment]
This behavior hasn't been modified in SESE, but I have noticed it being less reliable since the most recent version of SE, so it could be related to something there.
Sometimes it is necessary to collapse an item and then re-load it for the items it contains to be displayed. It makes little sense, since the same function is called either way.
I'm not going to put too terribly much effort into the GUI as it currently exists, since I plan to completely re-work it in a future version, anyway, and would rather not spend my effort on something that's just going to get replaced anyway.
So my recommendation would be to try that workaround first, as it seems to work for me. Let me know if you still can't see anything.

**Comment by dodexahedron** [comment]
Also, please update to 417 before trying again.

**Comment by dodexahedron** [comment]
Are you able to give me that last log from the actual log file? That looks potentially useful.

**Comment by tdmike** [comment]
I just updated to 417 but I wont start anymore (see below), and which log file should that be?

![untitled](https://cloud.githubusercontent.com/assets/6142706/7353165/ca58c0fa-ed11-11e4-8ef5-8a5bb54d2638.png)

This only happens with the following line: 

C:\dedicated-servers\space-engineers\DedicatedServer64\SEServerExtender.exe autostart instance="Survival" path="%programdata%\SpaceEngineersDedicated\Survival 2" restartOnCrash autosave=10

If I run it without autostart the server starts fine

Also sorry for the slow responses, apparently we are a lot of time zones apart :).

**Comment by dodexahedron** [comment]
How does this behave on *.418 and Essentials 2401?

**Comment by dodexahedron** [comment]
The original problem here has been solved, and the nullreferencexception has been fixed as well.
Closing this.
