### ISSUE TITLE
Developer Recruiting

### ISSUE THREAD

**Issue by togosh** [SEServerExtender/SEServerExtender#28]
More eyeballs, More hands, More brains.
More developers, more testers, more feedback, more ideas.

Ideas:
- Post recruitment ads online
  - Keen forums, Minecraft forums, C# forums, etc (please suggest more!)
  - Couple sentences about the project and what it does, what languages/tools does it use, link on how to get started (#27)
  - Cool graphic/poster/logo
- Actual recruitment web page
  - With an application
  - With a programming test

**Comment by dodexahedron** [comment]
This is already a planned idea, but it's waiting on some other things.
The most important thing it's waiting on is stability of the SE codebase.
I've already had around 20 people offer help to me and then just disappear.

Yes, I do want this to be more people and to grow into all that it can be, but it's just not that attractive to most "real" developers while the game is still in such rapid flux.

Marketing is interesting. You can totally launch too early. Right now, I feel, is too early, since there are things with SE that are changing significantly and will continue to change significantly until it's no longer alpha-stage.  People can be turned off by something that feels futile or unfinished.  Thoughts?

I mean.. This is really an alpha project supporting and supported by an alpha project.   It's alpha squared. :)

**Comment by qrokodial** [comment]
you'd have a lot more interest in the project if it had a clear and public documentation. right now no one can easily pick up the extender and write their own plugins/extensions for it without extensive research into how the extender works as a whole.

**Comment by dodexahedron** [comment]
As I was trying to say, that'll all come when SE itself is stable.
I'm not really putting any effort into that until things stabilize and some of the bigger redesigns are finished, because I really don't want a bunch of people to write plugins and then have the rug ripped out from under them in the middle of it all.
