### ISSUE TITLE
Characters no longer populating in GUI

### ISSUE THREAD

**Issue by joemorin73** [SEServerExtender/SEServerExtender#37]
In the SEServerExtender.exe GUI, character entities are not displaying on the entities tree.

**Comment by Ragnar24** [comment]
I am currently not having these issues on the .476 build. Do you have the most recent SESE?

**Comment by dodexahedron** [comment]
Wait... You're /not/ having this issue?
Seriously?

**Comment by Ragnar24** [comment]
It seems like this issue is similar to the ups. Sometimes the players are there and sometimes they are not. Earlier today, when I read this post, there were 4 people out of their ships and on the entities list. Now that I double checked there is no one on the entities tab while people are free floating.

**Comment by joemorin73** [comment]
It's for real.  I haven't seen characters since .80 update in the GUI.
