### ISSUE TITLE
x86 dlls

### ISSUE THREAD

**Issue by remygrandin** [SEServerExtender/SEServerExtender#4]
Hi,

I was starting to play around with the new WCF services to call them in SESM and, to use them i had to link the SEComm.dll and, obviously, the SEModAPIInternal.dll.

But, i fail tu build SESM because of ... X64 libraries ^^

So my request, if it's not blocking, can you compile in the futur releases the base SESE libraries in X86 ?

**Comment by dodexahedron** [comment]
The dedicated server is x64, so it makes little sense to compile for x86.
What toolchain are you using?  Any recent version of visual studio should be able to build for the x64 targets.

**Comment by remygrandin** [comment]
I can build for x64, yes,  but it would break compatibility for those who use SESM on a x86 computer (and they are quite a few).  Over the moment,  I've compiled the dlls myself in x86 for my WCF test and it worked well. A solution if you want to keep all your dlls in x64 would be to create another one, specifically to store all the WCF transfert object. In that way, it would allow both x86 and x64 software to easily consume the WCF service

**Comment by dodexahedron** [comment]
How can they use SESM on an x86 machine when SE is x64? I thought SESM ran on the same machine as SE?

-----Original Message-----

**Comment by remygrandin** [comment]
SE is published both as a x86 and a x64 version, that's why you have a dedicatedServer and a dedicatedServer64 folder ^^
I agree that 75% of users use the x64 but we can't neglect the 25% others

-------- Message d'origine --------
De : dodexahedron notifications@github.com
Date :25/03/2015 15:36 (GMT+01:00)
A : SEServerExtender/SEServerExtender SEServerExtender@noreply.github.com
Cc : GRANDIN Rémy Remy.GRANDIN@supinfo.com
Objet : Re: [SEServerExtender] x86 dlls (#4)

How can they use SESM on an x86 machine when SE is x64? I thought SESM ran on the same machine as SE?

-----Original Message-----

**Comment by dodexahedron** [comment]
Do we have any real statistics for people actually running x86 SE servers?  Seems like a really awful idea, considering how much memory this game uses.

Basically, I'm asking this: is it worth supporting 32-bit users instead of simply making it a requirement?
It's 2015...
I just dislike the idea of having to deal with more user confusion because of multiple versions.  Some people apparently find it hard enough to install it correctly with just one version out there.

I can compile with no bitness preference (MSIL build target), but that throws a lot of compiler warnings that are very legitimate (no guarantee of runtime stability, since things like the havok wrapper are compiled against explicit 32 and 64 bit targets).
It's even more of an issue if people are trying to do this under WINE or something, because then we're talking completely different runtime environments.

It's a simpler support situation to pick one specific thing to support and tell others "sorry - you don't meet the requirements" though yes, I realize that would leave a minority of users in the cold.

This isn't me putting my foot down and saying I won't do it - it's me stating my opinion on what I should do, and that opinion could very well need a sanity check.
What are your thoughts?

Also, anyone else watching who cares to weigh in on this?

**Comment by remygrandin** [comment]
I see your point,  however, with the following proposition,  I think we can have both x86 support for WCF client (and it's only for the WCF client that we need support here, not for the whole SESE  itself) and stay with a single version to support :

By moving all the WCF DTO (Data transfer objects, the objects needed as input or provided as output by the WCF service) into a separate dll, and by compiling ONLY this dll against x86, it would allow both x86 and x64 client to reference this dll and consume the WCF service without posing a threat to the overwhole stability.  As those DTO should technicly only be data storage classes,  with little to no "logic" (I mean code) in it,  it shouldn't be a problem to store them in an x86 container. 

I will also state again (sorry if I'm repeating myself ^^),  that we are talking here about x86 WCF CLIENT, support and not for the whole SESE server, which would of course raise a lot of problems as you highlighted. Also, as you rewrote the WCF by using a ws2007httpbinding instead of a named pipe (which is a looot better, thanks for that),  it was, I suppose, also mainly to provide eventually the possibility to connect remotely to the SESE trough the WCF service, and as I agree the x86 computer share on the server side are pretty thin,  it goes up when we are looking at clients ones. 

So, to conclude my statement,  I would say that as long as there is a way to keep a wider compatibility without threatening the overwhole stability, we should go for it!  ^^

**Comment by dodexahedron** [comment]
Well, for those using the WCF client, they're already programmers and they should be compiling SEComm.dll from code, anyway.
In that case, they can choose whatever build target they want.
I don't currently distribute SEComm.dll by itself for that reason.

**Comment by remygrandin** [comment]
Hmm, I see your point, you're right.
For the moment i will manualy recompile it as x86 for SESM. Please be sure to note in your changelogs if you change/add any WCF methods ^^

My concern was raise mainly as the other WCF projects i used in the past, the DTO were always in a separate dll, for the above reasons. It also saved time for the consumers, as they don't have to re-compile it.

Related but not necessary linked : i noticed when linking SEComm.dll that the linking of SEModAPIInternal.dll was also needed by visual studio, is this inteded behaviour (as the name suggest it's for SESE internal use only) ?

**Comment by dodexahedron** [comment]
SEModAPIInternal is just poorly named, and I haven't bothered to rename it from what it was originally named.

But yes, the reference is intentional, because types are used by SEComm.

**Comment by dodexahedron** [comment]
Closing this one, as I think we clarified what the intent is here.
Feel free to re-open if you think it warrants more discussion.
