### ISSUE TITLE
SEServerExtender Future

### ISSUE THREAD

**Issue by qrokodial** [SEServerExtender/SEServerExtender#46]
now that Keen has released the source code for SE, are there any plans on revamping the source code for SEServerExtender? if so, what will change, if not, why?

**Comment by dodexahedron** [comment]
A lot will change.
Since nothing is obfuscated and we have the real source, actual game classes can be used in almost all cases, instead of proxy classes.

**Comment by qrokodial** [comment]
that's what I figured. how will this impact development of new features? how about updating to new patches?

**Comment by dodexahedron** [comment]
In theory, it should make development of new things easier, once the refactoring is done.
As for patches, it shouldn't really be necessary to patch any more, so long as the game API doesn't change in a breaking way.  The only reason SESE used to have to be updated every week was because, when the code was obfuscated, several functions and classes changed names every single week to some other scrambled mess.  That is no longer an issue, which is why the version of SESE hasn't kept pace with SE lately.
In fact, because of that, we can probably go back to a more normal versioning system that doesn't have to stay in lock-step with SE any more.
Perhaps I will indicate that with a bump to version 2, after which we can follow SemVer rules.

**Comment by dodexahedron** [comment]
Considering SE keeps changing so rapidly and making breaking changes, I won't switch to semantic versioning just yet.  For now, I'm going to keep the versioning system as I've had it, and will switch to SemVer once the SE codebase becomes more stable.
