### ISSUE TITLE
Can't write assembly(dll file) for disabled plugin.

### ISSUE THREAD

**Issue by sjsoft2015** [SEServerExtender/SEServerExtender#58]
There is no way to replace the plugin assembly on the go. It is necessary to fix

**Comment by dodexahedron** [comment]
Can you explain what is happening for you?
SESE is explicitly built to allow on-the-fly reloading of plugins, and I use that quite a bit when working on essentials.  So if it's not working for you, I need to know exactly what's happening and exactly what you are doing.

**Comment by sjsoft2015** [comment]
http://youtu.be/5YiiUtETPsg

**Comment by dodexahedron** [comment]
Are you still experiencing this problem with the current version?
Are you having the problem with one of the plugins I maintain or with someone else's plugin?

**Comment by sjsoft2015** [comment]
nevermind, i do not use extender anymore. Because plugins update by tiimer thats cause problems and crashes....

**Comment by dodexahedron** [comment]
It's hard to fix a problem if it isn't explained and people just throw their hands up and jump ship...
Timers don't cause problems, inherently.
If there are problems, it's generally due to things not being done on the game thread.  Those problems are easily fixed if they are reported, but if it's all left up to me to just find by magic, I can't help anyone.  I simply do not have the time or resources to test every single facet of this application and all the possible things it can affect. I also, by extension, don't have the time or resources to test and troubleshoot each and every possible effect of the various plugins that depend on SESE.
I don't have infinite time, and I certainly don't have time during the past couple of weeks, because my wedding is next Saturday.
I'm the only person actively maintaining this, I do it for free, and I do it in the face of constant change and impatient users, after entire days of staring at a screen all day at my day job.
All I ask, when I get time to address an issue, is for a simple explanation of the problem.
If users can't be bothered to help me help them, when I have the chance to do so, then, frankly, I don't have the motivation or desire to help those users.
Some users go so far as to troubleshoot enough that, from all their descriptions of what has happened, the cause is obvious and I am able to fix it in minutes. Some users even go so far as to contribute a fix themselves and submit a pull request (which I am happy to review and merge into the codebase).
However, if I can't get a descriptive answer about what's happening, including logs (where appropriate), I can't be expected to drop everything else in my life and just make it happen.  This especially applies when the problem description can't even be narrowed down to something directly caused by SESE (as this issue).

I feel so strongly about this issue that I'm writing from my cell phone, far away from home, and far away from any computer capable of running visual studio. I'd rather be spending this time with my fiancee, but even she saw this comment and said "Wow. Entitled, much?"

I'm leaving this issue open in the hopes that either a more useful problem description can be given or that I can find, through some miracle, what was originally being complained about.  If I can't find the issue by the end of June, I'm going to close this regardless, with an "invalid" tag.

I cannot duplicate this issue with any of the plugins I support.
I need substantive evidence that this is actually a problem and I need specific reproduction steps or else I simply cannot provide support for this issue.
If a plugin I do not support is causing this problem, then the problem lies with that plugin and you should take it up with the author.

**Comment by SilentSymphony** [comment]
Don't you worry dodex, Most of us appreciate what you do, And understand you don't have all the time in the world, If I see anyone who doesn't I'll be sure to set them straight!

**Comment by sjsoft2015** [comment]
as i say nevermind. just close it.
I assume that this was due threads don't close properly. Maybe one of them was not closed when disconnecting the plugin.
