### ISSUE TITLE
Updating to 9.522 version grays out common program data selector unable to run SE

### ISSUE THREAD

**Issue by markam67** [SEServerExtender/SEServerExtender#59]
After updating the Server Extender files, like I have done many times before, upon starting the Server Extender the option to use common program data was grayed out and was unable to select any active game. If you start Server Extender at this point to starts up but begins to throw multiple errors. Not sure if I did something wrong but I was forced to jump back to 8.506

**Comment by markam67** [comment]
As an update I was able to run this version by using commandline args for instance and instance path. The selector box for common program data instance was clickable but contained no instances at all the use checkbox was still grayed out.

**Comment by dodexahedron** [comment]
Is it running with administrative permissions?
SE (and SESE) enumerate windows services to find the configured space engineers dedicated server instances, so it needs elevated permissions when you run it or that won't work.
That version of SESE changed to do it the same way that SE does.  Previously, it was trying to do it via another method that wasn't working in some cases.

**Comment by markam67** [comment]
I think that was part of the problem, I dont think I had running instances. I only had saved games from previous instances.  The old method was finding those and offering to run them. I will make sure I am running in admin mode and let you know.
Archmage

Date: Fri, 12 Jun 2015 07:41:59 -0700

**Comment by dodexahedron** [comment]
Just because I intend to keep this working the same way that the game does it, I recommend you set your dedicated server instances up through the dedicated server tool provided by keen.
All it really does is creates the folders, config files, and the service entry for a new instance of the game, anyway (which hey - maybe I could put that in Extender itself at some point).
Is the way keen does it the best way to do what they're doing? Meh..Not really.. But it's the way it's being done, so until or unless that changes, SESE will do the same thing.

Let me know if you have any trouble.
I'm going to go ahead and close this issue.
