### ISSUE TITLE
WCF Service not responding

### ISSUE THREAD

**Issue by remygrandin** [SEServerExtender/SEServerExtender#6]
When I launch SESE as a service, the WCF service don't seam to resond, at least, not on the port i define at service start
Edit : not on the 5353 default either

Here is an exemple of my starting arguments : 

nogui
noconsole
wcfport=26016
autosave=10
instance=SESM_1_test
gamepath=c:\SpaceEngineers\

With this log I assume it detect well the argumets : 
    2015-03-24 15:09:27.5569|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 6 arguments ...

Also, the log indicate the WCF started : 
   2015-03-24 15:09:27.9621|Info|SEServerExtender.Program.Start|Opening up WCF service listener

**Comment by dodexahedron** [comment]
wcfport is not a valid parameter.
The WCF service is configured via the .config file only.

**Comment by remygrandin** [comment]
Well, so I'll change this from a bug report to a feature request ^^ :
Can we have a way to specify the WCF port somewhere else than the main config file. Either through the startup args (as it was the case before) or through an instance specific config file? 

Also,  as I see it coming, duplicating the instance is simply not an option : I know of people with more than 50 instance on a same host,  it would force them to have like 25GB of pure dead weight of duplicate files, which is not a healthy solution,  especially as they use an SSD as drive, where used space matter :-)

**Comment by dodexahedron** [comment]
I'm going to do this a different way.
Being WCF, port sharing is already possible, so we don't need to specify port.
But, each instance does still need to listen on a unique URL.
So, I'll probably do this so that each instance listens on a URL that includes the instance name, so that they are all unique.  This should solve the problem going forward, as well as give a much more obvious means of identifying which URL belongs to which running server.

**Comment by dodexahedron** [comment]
This is released in version 1.76.11.367
