### ISSUE TITLE
Norton detecting a security risk with SESE

### ISSUE THREAD

**Issue by FoxWyvern** [SEServerExtender/SEServerExtender#65]
I can no longer download SESE without Norton immediately deleting it. Below is a link that Norton forwards to. I am also having the file apparently being removed from my dedicated server as well.

http://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99&vid=4294919973&prod=scss&product=Norton%20Security%20Suite&version=21.7.0.11&plang=sym:EN&layouttype=SOS&buildname=SymantecPartner&heartbeatID=472EC9F1-8927-465D-BDB2-DEE0610C2CFD&env=prod&ispid=1122&sitename=US&vendorid=Symantec&plid=0&skup=21317287&skum=21317287&skuf=21291129&endpointid={472EC9F1-8927-465D-BDB2-DEE0610C2CFD}&partnerid=Symantec&lic_type=64&lic_attr=152594&osvers=6.1&oslocale=iso:USA&oslang=iso:ENG&os=windows

**Comment by dodexahedron** [comment]
That's because you have it set WAY too high.
Nothing created by the community is ever going to pass that check.
Disable the reputation check, and just don't download things you aren't sure of.
For those who are super-paranoid, that's why I digitally sign all binaries I release, here. So, if the digital signature is missing or invalid, then you know you have gotten your hands on an altered/tampered-with release.
Otherwise, this is just one in a very long string of false positives you're going to get if you leave that reputation check on.

**Comment by dodexahedron** [comment]
Also, please go here and report the false positive: https://submit.symantec.com/false_positive/
